source 'https://github.com/CocoaPods/Specs.git'

target 'DXCustomCallout-ObjC', :exclusive => true do
  pod "DXCustomCallout-ObjC", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DXCustomCallout-ObjC", :path => "../"

  
end
